### ISSUE TITLE
Add reverse DNS for location

### ISSUE THREAD

**Issue by avacore1337** [avacore1337/queueSystem#14]
A persons location should be determined by reverse DNS for convenience.

**Comment by antbac** [comment]
This is done now, but there is no square with a color next to the location as there is in QWait yet.

**Comment by avacore1337** [comment]
It has color square but  stability needs to be improved. If error it should default to no location. We should possibly make it work for proxies.

**Comment by antbac** [comment]
This should hopefully be stable enough now.
