### ISSUE TITLE
Server wide message behaving weird

### ISSUE THREAD

**Issue by avacore1337** [avacore1337/queueSystem#15]
Currently the server wide message is only shown when logging in and not broadcasted, is this really what was decided?

**Comment by avacore1337** [comment]
The implementation probably needs a rework since the code for the sockets seems weird and duplicated.

**Comment by avacore1337** [comment]
Fixed the weird implementation but functionality remains the same.

**Comment by antbac** [comment]
This should broadcast to everyone connected to the server and give the message to people upon loggin in like it does now.

**Comment by antbac** [comment]
It now shows the message to everyone connected to the server, and then to everyone who logs in after that.
