### ISSUE TITLE
change user usage flow.

### ISSUE THREAD

**Issue by avacore1337** [avacore1337/queueSystem#5]
currently there are four normal flow options for a user. It's:
Enter -> Leave (because getting help)
Enter -> Leave (gave up)
Enter -> Getting marked by TA as getting help -> Leave/get kicked
Enter -> Getting marked by TA as getting help -> Unmarked as getting help (in case assistant is unable to help/complete the task)

All paths should go through the getting help phase unless the student changed his mind or simply gave up (for whatever reason).
I would suggest the following flows. 
Enter -> Leave (gave up)
Enter -> Getting marked by TA or self as getting help -> Leave/get kicked (because finished)
Enter -> Getting marked by TA or self as getting help -> Unmarked by TA as getting help (in case assistant is unable to help/complete the task)

This makes it easier to classify when generating statistics. It should be implemented by giving the student the option to mark himself as getting help but not giving him the option to unmark himself since it might be abused otherwise.

**Comment by antbac** [comment]
This has been resolved now.
